"""SDD infrastructure package."""

from sdd_server.infrastructure.config import (
    DEFAULT_CONFIG_DIR,
    DEFAULT_CONFIG_FILE,
    AuditSettings,
    Environment,
    ExecutionConfig,
    HealthCheckSettings,
    LoggingConfig,
    LogLevel,
    MetricsSettings,
    ObservabilityConfig,
    PluginConfig,
    RateLimitSettings,
    RetrySettings,
    SDDConfig,
    SecurityConfig,
    ServerConfig,
    get_config,
    reload_config,
)
from sdd_server.infrastructure.exceptions import (
    AlreadyInitializedError,
    ConfigurationError,
    ErrorCode,
    ErrorContext,
    ExecutionCancelledError,
    ExecutionError,
    ExecutionTimeoutError,
    FileNotFoundError_,
    FileSystemError,
    GitError,
    GitNotARepoError,
    GooseNotFoundError,
    InputValidationError,
    NotInitializedError,
    PathTraversalError,
    PluginError,
    PluginLoadError,
    PluginNotFoundError,
    PluginValidationError,
    RecipeNotFoundError,
    SDDError,
    SecurityError,
    SpecNotFoundError,
    SpecParseError,
    ValidationError,
)
from sdd_server.infrastructure.observability import (
    AuditEvent,
    AuditEventType,
    AuditLogger,
    Counter,
    Gauge,
    HealthCheck,
    HealthCheckRegistry,
    HealthCheckResult,
    HealthStatus,
    Histogram,
    MetricsCollector,
    Timer,
    audit_log,
    get_audit_logger,
    get_metrics,
    health_check_registry,
    metric_counter,
    metric_timer,
    run_health_checks,
)
from sdd_server.infrastructure.retry import (
    AsyncRetryContext,
    RetryConfig,
    RetryContext,
    RetryExhaustedError,
    RetryResult,
    RetryStrategy,
    async_retry,
    is_retryable_exception,
    retry_on_exception,
    retry_on_file_lock,
    retry_on_timeout,
    sync_retry,
)
from sdd_server.infrastructure.security import (
    InMemoryRateLimiter,
    InputSanitizer,
    InputValidator,
    PathValidator,
    RateLimitConfig,
    RateLimiter,
    RateLimitExceeded,
    TokenBucketRateLimiter,
    get_rate_limiter,
    rate_limit,
    sanitize_filename,
    sanitize_html,
    validate_feature_name,
    validate_path,
    validate_spec_content,
)

__all__ = [
    # Config
    "DEFAULT_CONFIG_DIR",
    "DEFAULT_CONFIG_FILE",
    "AlreadyInitializedError",
    "AsyncRetryContext",
    # Observability - Audit logging
    "AuditEvent",
    "AuditEventType",
    "AuditLogger",
    # Config - Audit
    "AuditSettings",
    "ConfigurationError",
    # Observability - Metrics
    "Counter",
    # Config - Environment
    "Environment",
    "ErrorCode",
    "ErrorContext",
    "ExecutionCancelledError",
    # Config - Execution
    "ExecutionConfig",
    "ExecutionError",
    "ExecutionTimeoutError",
    "FileNotFoundError_",
    "FileSystemError",
    "Gauge",
    "GitError",
    "GitNotARepoError",
    "GooseNotFoundError",
    # Observability - Health checks
    "HealthCheck",
    "HealthCheckRegistry",
    "HealthCheckResult",
    # Config - Health
    "HealthCheckSettings",
    "HealthStatus",
    "Histogram",
    "InMemoryRateLimiter",
    "InputSanitizer",
    "InputValidationError",
    # Security - Input validation
    "InputValidator",
    # Config - Log level
    "LogLevel",
    # Config - Logging
    "LoggingConfig",
    "MetricsCollector",
    # Config - Metrics
    "MetricsSettings",
    "NotInitializedError",
    # Config - Observability
    "ObservabilityConfig",
    "PathTraversalError",
    "PathValidator",
    # Config - Plugin
    "PluginConfig",
    "PluginError",
    "PluginLoadError",
    "PluginNotFoundError",
    "PluginValidationError",
    "RateLimitConfig",
    "RateLimitExceeded",
    # Config - Rate limit
    "RateLimitSettings",
    # Security - Rate limiting
    "RateLimiter",
    "RecipeNotFoundError",
    # Retry utilities
    "RetryConfig",
    "RetryContext",
    "RetryExhaustedError",
    "RetryResult",
    # Config - Retry
    "RetrySettings",
    "RetryStrategy",
    # Config - Main
    "SDDConfig",
    # Exceptions
    "SDDError",
    # Config - Security
    "SecurityConfig",
    "SecurityError",
    # Config - Server
    "ServerConfig",
    "SpecNotFoundError",
    "SpecParseError",
    "Timer",
    "TokenBucketRateLimiter",
    "ValidationError",
    "async_retry",
    "audit_log",
    "get_audit_logger",
    # Config - Get config
    "get_config",
    "get_metrics",
    "get_rate_limiter",
    "health_check_registry",
    "is_retryable_exception",
    "metric_counter",
    "metric_timer",
    # Config - Rate limit decorator
    "rate_limit",
    # Config - Reload config
    "reload_config",
    "retry_on_exception",
    "retry_on_file_lock",
    "retry_on_timeout",
    "run_health_checks",
    "sanitize_filename",
    "sanitize_html",
    "sync_retry",
    "validate_feature_name",
    "validate_path",
    "validate_spec_content",
]
